### ISSUE TITLE
IndexError: ('list index out of range', 'occurred at index 47')

### ISSUE THREAD

**Issue by potatoper** [plkmo/BERT-Relation-Extraction#16]
Please help,when I run the main_task.py,it occurred the error: 
           IndexError: ('list index out of range', 'occurred at index 47') (main_pretraining.py)
I tried all I can but it just didn't work.

            please help , xiexie

**Comment by plkmo** [comment]
Seems that somehow your semeval data is corrupted. Anyway, I have updated with code to filter out such data rows. Please try again.
