### ISSUE TITLE
Where can download the pre-training dataset cnn.txt?

### ISSUE THREAD

**Issue by bluesea0** [plkmo/BERT-Relation-Extraction#2]
In main_pretaining.py, line 21:
`    parser.add_argument("--pretrain_data", type=str, default="./data/cnn.txt", \
                        help="pre-training data .txt file path")`

I don't find the cnn.txt. So where can downnload it? Thanks.
[https://cs.nyu.edu/~kcho/DMQA/](url) Did you download it here？

**Comment by plkmo** [comment]
I have included the link to download the file in readme. Specifically you can download it here https://drive.google.com/file/d/1aMiIZXLpO7JF-z_Zte3uH7OCo4Uk_0do/view?usp=sharing. Its compiled from CNN dataset.
