### ISSUE TITLE
Output type rather than [CLS] is supported?

### ISSUE THREAD

**Issue by amirj** [plkmo/BERT-Relation-Extraction#28]
In the original paper, different input/output types are evaluated (please look at [Table 1](https://www.aclweb.org/anthology/P19-1279.pdf)), it seems that current implementation only support [[CLS] output type](https://github.com/plkmo/BERT-Relation-Extraction/blob/7e291ae49ed8d49ecd60321d5271ef30408ad92c/src/model/BERT/modeling_bert.py#L401-L402).

Does it correct or I missed something?

Thanks.

**Comment by plkmo** [comment]
As stated, we are using BERT_EM, which uses ENTITY MARKERS input representation
and ENTITY START output representation
