### ISSUE TITLE
Question: publish model predictions

### ISSUE THREAD

**Issue by ofersabo** [plkmo/BERT-Relation-Extraction#4]
Hi,

I would like to ask you to publish your trained model when it is only trained on TACRED ( without the matching the blanks training on Wikipedia).
I want to see the model prediction per instance when the model is trained based on TACRED only.  
Alternatively, if you could share with me the command to train your model only based on TACRED.

All the Best,

**Comment by plkmo** [comment]
Hi, I do not have paid access to TACRED. If you could share with me the dataset (or a sample of it), I can modify the preprocessing code accordingly to include TACRED training. Thanks.

**Comment by ofersabo** [comment]
Oh, no I can't to that. 
Thanks
