### ISSUE TITLE
Why is num_classes a command line argument and not directly inferred?

### ISSUE THREAD

**Issue by demongolem-biz** [plkmo/BERT-Relation-Extraction#41]
I take `num-classes` to be the distinct number of relation classes which can be annotated against and predicted.  With this statement, I struggle with the two following points:

1) If we are telling the training code how many classes there are, shouldn't we be telling it which classes we are using?
2) Shouldn't we be able to look at the training data and pick out how many classes there are and what they are?  This would seem the most sensible solution.

**Comment by plkmo** [comment]
Yes you're right. I've added this argument as sort of a sanity check, but it could be removed
