### ISSUE TITLE
Files of BioBERT Lost

### ISSUE THREAD

**Issue by ljy0ustc** [plkmo/BERT-Relation-Extraction#44]
Hi,

Thanks for providing the biobert code.

To use BioBERT(biobert_v1.1_pubmed), download & unzip the [contents](https://drive.google.com/file/d/1zKTBqqrCGlclb3zgBGGpq_70Fx-qFpiU/view?usp=sharing) to ./additional_models folder.

However, this link is not useful now.

Where could I get the contents?

**Comment by plkmo** [comment]
I have updated the link in the readme, please refer to it
