### ISSUE TITLE
Change the way "en_core_web_sm" is loaded to fix OSError: [E050]

### ISSUE THREAD

**Issue by markusheimerl** [plkmo/BERT-Relation-Extraction#48]
Hello,

if we change line 420 in /src/preprocessing_funcs.py from 
`nlp = spacy.load("en_core_web_lg")`
to
`nlp = en_core_web_sm.load()`
and add 
`import en_core_web_sm`
at the beginning of the file, the error 
`OSError: [E050] Can't find model 'en_core_web_lg'. It doesn't seem to be a Python package or a valid path to a data directory.`
is fixed.
(As described here https://github.com/explosion/spaCy/issues/4577)

**Comment by plkmo** [comment]
Thanks for the suggestion. I have added a requirements.txt file & instructions to download the space model, so this error should be resolved in the future
