### ISSUE TITLE
zero f1

### ISSUE THREAD

**Issue by xiongjun19** [plkmo/BERT-Relation-Extraction#7]
Hi, plkmo ! 
I have managed to run the main_task script using follow command:
`python main_task.py --train_data ./data/finetune/SemEval2010_task8_all_data/SemEval2010_task8_training/TRAIN_FILE.TXT --test_data ./data/finetune/SemEval2010_task8_all_data/SemEval2010_task8_testing_keys/TEST_FILE_FULL.TXT --use_pretrained_blanks 0 --model_no 0`
but always got  zero f1 in about 20 ecpos, you can see the detail in following:

`Epoch finished, took 29.90 seconds.
Losses at Epoch 20: 2.6830234
Train accuracy at Epoch 20: 0.1756250
Test f1 at Epoch 20: 0.0000000`

**Comment by plkmo** [comment]
What is the other arguments used for main_task.py? Can you try running with default arguments?
